apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-o6sr
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0077-tenant/ci10t-776-0077-app/devfile-sample-o6sr@sha256:34bb22d4b02f4bdae971e0599885f27b67ddf663349488e092552386c9bd965d
        name: my-nodejs
        resources: {}
status: {}
